config/routes.rb
BoardTestV1O::Application.routes.draw do
  resources :groups
  resources :users
  # resources :sessions

  root 'groups#index'
  get   'login' => 'sessions#new'
  post  'create_login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'


end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to groups_path, notice:'新增討論版成功'
    else
      render :new
    end
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to groups_path, notice: '修改討論版成功'
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path, alert: '討論版已刪除'
  end
end
private

def group_params
  params.require(:group).permit(:title, :description)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:userid] = user.id
      redirect_to groups_path
    else
      render :new
    end
  end

  def destroy
    session[:userid] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    # instance variable
    @user = User.new
  end

  def create
    # render :new
    @user = User.new(user_param)
    @user.save
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
    def user_param
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { :notice => :success, :alert => :danger }

    close_button_options = { :class => "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "X", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2014 Rails101s
    <br>Design by <a href="http://sdlong.logdown.com" target=_new>sdlong</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails 101</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% unless session[:userid].present? %>
          <li> <%= link_to("登入", login_path) %> </li>
          <li> <%= link_to("註冊", new_user_path) %> </li>
        <% else %>
          <li> <%= link_to("登出", logout_path, method: :delete) %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
<h1>修改討論版</h1>

<hr>
<%= simple_form_for @group do |f| %>
  <%= f.input :title, :input_html => { :class => "form-control"} %>
  <%= f.input :description, :input_html => { :class => "form-control"} %>
<hr>
  <%= f.submit "Submit", :disable_with => 'Submitting...', :class => "btn btn-primary"%>
<% end %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("新增留言", new_group_path , class: "btn btn-primary pull-right" ) %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <td> # </td>
        <td> Title </td>
        <td> Description </td>
      </tr>
    </thead>

    <tbody>
            <% @groups.each do |group| %>
    <tr>
      <td> # </td>
      <td>  <%= link_to(group.title, group_path(group)) %> </td>
      <td>  <%= group.description %> </td>
      <td>  <%= link_to("編輯",
                        edit_group_path(group),
                        class: "btn btn-sm btn-default")%>

            <%= link_to("刪除",
                        group_path(group),
                        class: "btn btn-sm btn-default",
                        method: :delete,
                        data: { confirm: "Are you sure?" } )%></td>
    </tr>
            <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
<h1>新增討論版</h1>

<hr>
<%= simple_form_for @group do |f| %>
  <%= f.input :title, :input_html => { class: "form-control"} %>
  <%= f.input :description, :input_html => { class: "form-control"} %>
<hr>
  <div class="form-actions">
    <%= f.submit "Submit", data: { disable_with: 'Submiting...' }, class: "btn btn\
-primary"%>
  </div>
<% end %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("Edit", edit_group_path(@group) , :class => "btn btn-primary pull-right")%>
  </div>
  <h2> <%= @group.title %> </h2>
  <p> <%= @group.description %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoardTestV1O</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render "common/navbar" %>
    <%= notice_message  %>
    <%= yield %>
  </div>
  <%= render "common/footer" %>
</body>
</html>

app/views/users/index.html.erb
<div>
<% @users.each do |user| %>
<h1>歡迎!<%= user.name  %></h1>
<th>
<p>感謝你的註冊</p>
<%= link_to("刪除",
                        user_path(user),
                        class: "btn btn-sm btn-default",
                        method: :delete,
                        data: { confirm: "Are you sure?" } )%>
<% end %>
</div>

app/views/users/new.html.erb
<div class="col-md-4 col-md-offset-4">
<h1>註冊</h1>
<%= simple_form_for @user do |f| %>

    <%= f.input :name ,input_html: { class: "form-control"}%>

    <%= f.input :email ,input_html: { class: "form-control"}%>
    <%= f.input :password ,input_html: { class: "form-control"}%>
    <%= f.input :password_confirmation ,input_html: { class: "form-control"}%>
  <!-- <div class="form-actions"> -->
    <br>
    <%= f.submit "確認" , data: { disable_with: 'Loading...' }, class: "btn btn\
-primary"%>
  <!-- </div> -->
<% end %>
</div>